#include "data/scripts/dc_elmers/config.h"

#import "data/scripts/dc_elmers/bind.c"
#import "data/scripts/dc_elmers/entity.c"
#import "data/scripts/dc_elmers/instance.c"
#import "data/scripts/dc_elmers/level.c"
#import "data/scripts/dc_elmers/macro.c"
#import "data/scripts/dc_elmers/offset.c"
#import "data/scripts/dc_elmers/palette.c"
#import "data/scripts/dc_elmers/position.c"
#import "data/scripts/dc_elmers/position_config.c"